title: 搁浅St的blog
subtitle: 我最喜欢笨笨
description: jackroyal 博客 搁浅St 笨笨
author: jackroyal
language: zh-CN
timezone: null
url: 'https://bblove.me'
root: /
permalink: ':year/:month/:day/:title/'
permalink_defaults: null
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: ':lang'
skip_render: null
new_post_name: ':title.md'
default_layout: post
titlecase: false
external_link: true
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace: null
default_category: uncategorized
category_map: null
tag_map: null
date_format: YYYY-MM-DD
time_format: 'HH:mm:ss'
per_page: 10
pagination_dir: page
index_generator:
  per_page: 10
archive_generator:
  per_page: 20
  yearly: true
  monthly: true
tag_generator:
  per_page: 20
category_generator:
  per_page: 20
sitemap:
  path: sitemap.xml
feed:
  type: atom
  path: atom.xml
  limit: 20
duoshuo_shortname: jackroyal
theme: fexo
deploy:
- type: git
  repo: 'https://github.com/Jackroyal/Jackroyal.github.io.git'
  branch: master
- type: git
  repo: git@bblove.me:/home/git/bblove/blog.git
  branch: master
get: registry
