# Blog info
blog_name: 搁浅St
slogan: 我最喜欢笨笨
url: https://bblove.me

# Set avatar (Absolute url and relative url)
avatar: /images/avatar.jpg

# Set favicon
favicon: /favicon.ico

# For seo
keywords: 搁浅St,blog,笨笨

home_nav:
  - name: Blog
    url: /archives
    target_blank: false #不在新页面打开
  # - name: Project
  #   url: /project/
  #   target_blank: true #在新页面打开
  - name: Github
    url: https://github.com/jackroyal
    target_blank: true
  - name: Weibo
    url: http://weibo.com/517123263
    target_blank: true

# config page nav
page_nav:
  - name: 博客
    url: /archives/
    target_blank: false # 不在新页面打开
  - name: 分类
    url: /category/
    target_blank: false
  - name: 标签
    url: /tag/
    target_blank: false
  - name: 友链
    url: /link/
    target_blank: false
  - name: 关于
    url: /about/
    target_blank: false
  - name: RSS
    url: /atom.xml
    target_blank: true # 在新页面打开
  - name: 搜索
    url: /search/
    target_blank: false # 在新页面打开

page_nav_style: CIRCLE  # CIRCLE|ROUND_RECT

# 面包屑
breadcrumb:
  isShow: true # true|fase

# 盒子
toolbox:
  isShow: true # true|fase
  text: 点我

search_slogan:
  isShow: true # true|fase
  text: 输入关键词开始搜~搜~~

link_slogan:
  isShow: true # true|fase
  text: 我的小伙伴儿们


# set backtop show or hide
backtop:
  home: false
  archive: false
  category: true
  tag: true
  post: true
  link: false
  about: false

donation:
  show: true
  btn_text: 支持一下
  tip: 扫一扫，试试看
  items:
    - type: 微信
      text: 微信扫一扫
      imgUrl: https://ww1.sinaimg.cn/large/692869a3gw1exhxpgwag0j20dg0deabz.jpg
    - type: 支付宝
      text: 支付宝扫一扫
      imgUrl: https://ww4.sinaimg.cn/large/692869a3gw1esp065y3aaj207i07i74o.jpg




post:
  header_align: CENTER # LEFT|CENTER
  showToc: true # true|false
  showComments: true
  open_in_new_window: false
  show_prev_next: true

# =========================================================
# 个性化设置
# =========================================================

# Custom CSS style, 推荐把样式文件放在blog源码文件夹，而不是主题里面
personal_style: /css/geqianst.css

# 这个值取决于你得背景图片是深色还是浅色，深色用dark，浅色用light
home_background_scheme: dark # dark、light

# custom font-family 暂时只支持这3种英文字体，你可以完全自定义字体(看文档)
blog_name_font_familiy: yhlkb
# blog_name_font_familiy: Lobster-Regular
# blog_name_font_familiy: PoiretOne-Regular

init_page_content: HOME_NAV  # HOME_NAV | POST


# =========================================================
# 第三方服务
# =========================================================
# Stats
google_analytics:
baidu_analytics: 13ec0256b3333d6ccd6fe91326368508

# Comment service
# disqus_shortname: jackroyal
duoshuo_shortname: jackroyal
# gentie_key: d16a7241e7cd4b389584ed8db2a4e8bc

# 不算子,文章访问量统计和显示
busuanzi: false

# =========================================================
# 页面内容设置
# =========================================================
about:
  - type: me
    icon: icon-user
    text_value:
    - "喜欢编程,热爱技术."
    - "后端开发工程师，常用 PHP / JavaScript."
    - "以后,会成为一名全栈工程师."
  - type: Github
    icon: icon-github
    text_key: Github
    text_value: "@jackroyal"
    text_value_url: https://github.com/jackroyal
  - type: weibo
    icon: icon-weibo
    text_key: 微博
    text_value: "@搁浅St"
    text_value_url: https://weibo.com/u/517123263
  # - type: mail
  #   icon: icon-mail
  #   text_key: Gmail
  #   text_value: "forsigner@gmail.com"
  - type: location
    icon: icon-location
    text_value: 武汉
link:
  - name: Star
    info: 做快乐的自己
    url: https://huirongis.me
    avatar: https://huirongis.me/images/avatar.jpg
  - name: 宝盖头的blog
    info:
    url: http://moonmoonmoon.github.io
    avatar: https://avatars0.githubusercontent.com/u/6274940?v=3&s=460
  - name: 老谭的blog
    info:
    url: https://WeedT.github.io
    avatar: https://avatars0.githubusercontent.com/u/9836270?v=3&s=460
  - name: 王大锤的blog
    info:
    url: https://wustchuichui.github.io
    avatar: https://avatars3.githubusercontent.com/u/18179631?v=3&s=460

project:
  - type: personal
    name: fexo
    url: https://github.com/forsigner/fexo
    intro: A minimalist design theme for hexo
  # - type: company
  #   name: Fexo
  #   url: https://github.com/forsigner/fexo
  #   intro: A minimalist design theme for hexo
  # - type: personal
  #   name: beside
  #   url: https://github.com/forsigner/beside
  #   intro: I need you beside me
  # - type: personal
  #   name: web-fontmin
  #   url: https://github.com/forsigner/web-fontmin
  #   intro: 字体子集化，在线提取你需要的字体
  # - type: personal
  #   name: magic-check
  #   url: https://github.com/forsigner/magic-check
  #   intro: Beautify Radio and Checkbox with pure CSS
  # - type: personal
  #   name: nice-bar
  #   url: https://github.com/forsigner/nice-bar
  #   intro: A nice and lightweight scrollbar
  # - type: personal
  #   name: angular-nice-bar
  #   url: https://github.com/forsigner/angular-nice-bar
  #   intro: A nice and lightweight scrollbar in Angular
  # - type: personal
  #   name: fo-popover
  #   url: https://github.com/forsigner/fo-popover
  #   intro: A nice popover for Angular
  # - type: personal
  #   name: fo-tooltip
  #   url: A nice tooltip for Angular
  #   intro: https://github.com/forsigner/fo-tooltip
  # - type: personal
  #   name: fo-modal
  #   url: https://github.com/forsigner/fo-modal
  #   intro: A nice modal for Angular
  # - type: personal
  #   name: mocer
  #   url: https://github.com/forsigner/mocer
  #   intro: Setup a mock server easily
  # - type: personal
  #   name: node-pngdefry
  #   url: https://github.com/forsigner/node-pngdefry
  #   intro: Repairing iPhone fried PNGs using Node.js
  # - type: personal
  #   name: ng-simditor
  #   url: https://github.com/forsigner/ng-simditor
  #   intro: Angular directive for simditor
